version: "3.4"
services:
  myapi:
    image: node-api-ts
    container_name: node-api-ts
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - ENV=local
    environment:
      - ENV=local
    ports:
      - "8000:3000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks:
      - rede
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'hackaton'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - type: bind
        source: ./mysql-data
        target: /var/lib/mysql
    networks:
      - rede
networks:
  rede:
    external:
      name: rede